### PR TITLE
Fix contHACKs accepting name with numbers

### LINKED ISSUE #188: [PE-D] Names can include numbers
Probably shouldn't be allowed

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jonas-chow/ped#15

### LINKED ISSUE #191: [PE-D] Accept Invalid name
Add command allow name to have number

Input: add n/101 e/ben123@gmail.com m/CS2103T T12 p/91238456 h/@BenIsHere r/Overseas

Expectation: Reject with error message

Actual:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jeromewjj/ped#8

### PR DESCRIPTION
**Pull request by tanruiquan**
`Name` should only contain alphabetic characters and spaces, and should not be blank.

Resolves #191 
Resolves #188

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Name.java [hunk 1]
```diff
@@ -10,13 +10,13 @@
 public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names should only contain alphabetic characters and spaces, and it should not be blank";
```
Comment (czhi-bin) [inline src/main/java/seedu/address/model/person/Name.java:13]: Would this be better?
```suggestion
            "Names should only contain alphabets and spaces, and it should not be blank";
```

**Review by czhi-bin — APPROVED** [review]
LGTM!

File: src/main/java/seedu/address/model/person/Name.java (hunk 1 above)
Comment (tanruiquan) [reply src/main/java/seedu/address/model/person/Name.java:13]: Good suggestion! I'll make the changes
