### PR TITLE
Fix bug in find person feature

### LINKED ISSUE #176: [PE-D] Wrong result of Find command
Step to reproduce:
1. Have contact(s) with module code CS2040
2. `f m/cs2040s`

Result:
- contacts with module CS2040 are matched, although CS2040 and CS2040S are not the same and CS2040S should not match CS2040

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nataniayp/ped#4

### PR DESCRIPTION
**Pull request by jason-ng-zq99**
If I have a contact with module CS2040, searching by module with keyword `CS2040S`
should not return that contact.

Fixed this behaviour by removing now obsolete `[MODULE_CODE]` string representation
of module codes, and checking whether `moduleCode.value` contains search keyword,
and not the other way round

To be clear, if I have the following contacts with the respective module codes:
* A: CS2040
* B: CS2030
* C: CS2030S

Searching:
* `find m/CS2040S` will return nothing
* `find m/CS2030` will return both B and C
* `find m/CS2030S` will only return B

Also, to better fit UG description, `find n/ce Y` should only return `Bernice Yu`, and not every contact that has the alphabet `Y`.
Similarly, `find n/Bob Carol` should not return an `Alice Carol`

Resolves #176, #179, #195, #172

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java [hunk 1]
```diff
@@ -102,7 +102,7 @@ public void execute_validLessonCodeUnfilteredList_success() {
         Set<LessonCode> lessonCodeToDelete = new HashSet<>();
         lessonCodeToDelete.add(new LessonCode("T12"));
         DeletePersonCommand deletePersonCommand = new DeletePersonCommand(new ModuleCodesContainsKeywordsPredicate(
-                Arrays.asList(String.format("[%s]", VALID_MODULE_CODE_CS2100 + " T12"))),
+                Arrays.asList(String.format("%s", VALID_MODULE_CODE_CS2100 + " T12"))),
```
Comment (driip-ddrop) [inline src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:105]:
```suggestion
                Arrays.asList(String.format("%s", VALID_MODULE_CODE_CS2100))),
```
you can delete all the classes behind in the ModuleCodeContainsKeywordsPredicate.

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java [hunk 2]
```diff
@@ -123,7 +123,7 @@ public void execute_editValidLessonCodeUnfilteredList_success() {
         Set<LessonCode> lessonCodeToDelete = new HashSet<>();
         lessonCodeToDelete.add(new LessonCode("T12"));
         DeletePersonCommand deletePersonCommand = new DeletePersonCommand(new ModuleCodesContainsKeywordsPredicate(
-                Arrays.asList(String.format("[%s]", VALID_MODULE_CODE_CS2106 + " T12"))),
+                Arrays.asList(String.format("%s", VALID_MODULE_CODE_CS2106 + " T12"))),
```
Comment (driip-ddrop) [inline src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:126]: same as above

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java [hunk 3]
```diff
@@ -145,7 +145,7 @@ public void execute_removeOneLessonCodeTagUnfilteredList_success() {
         Set<LessonCode> lessonCodeToDelete = new HashSet<>();
         lessonCodeToDelete.add(new LessonCode("L08"));
         DeletePersonCommand deletePersonCommand = new DeletePersonCommand(new ModuleCodesContainsKeywordsPredicate(
-                Arrays.asList(String.format("[%s]", VALID_MODULE_CODE_CS2100 + " L08"))),
+                Arrays.asList(String.format("%s", VALID_MODULE_CODE_CS2100 + " L08"))),
```
Comment (driip-ddrop) [inline src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:148]: same as above

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java [hunk 4]
```diff
@@ -200,7 +200,7 @@ public void execute_invalidMultipleModuleCodeUnfilteredList_throwsCommandExcepti
     @Test
     public void execute_invalidLessonCodeUnfilteredList_throwsCommandException() {
         ModuleCodesContainsKeywordsPredicate predicate = new ModuleCodesContainsKeywordsPredicate(
-                Arrays.asList(String.format("[CS2030S T1]")));
+                Arrays.asList(String.format("CS2030S T1")));
```
Comment (driip-ddrop) [inline src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:203]: same as above

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java [hunk 5]
```diff
@@ -188,7 +188,7 @@ public void execute_invalidModuleCodeUnfilteredList_throwsCommandException() {
     @Test
     public void execute_invalidMultipleModuleCodeUnfilteredList_throwsCommandException() {
```
Comment (driip-ddrop) [inline src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:189]: If this test case fails I think can delete. I'm going to change the parser such that it will not be possible to pass in 2 module codes into the predicate

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java (hunk 1 above)
Comment (jason-ng-zq99) [reply src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:105]: Thanks!

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java (hunk 2 above)
Comment (jason-ng-zq99) [reply src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:126]: Thanks!

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java (hunk 3 above)
Comment (jason-ng-zq99) [reply src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:148]: Thanks!

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java (hunk 4 above)
Comment (jason-ng-zq99) [reply src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:203]: Thanks!

File: src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java (hunk 5 above)
Comment (jason-ng-zq99) [reply src/test/java/seedu/address/logic/commands/person/DeletePersonCommandTest.java:189]: Yeap I had to delete, thanks!

**Review by driip-ddrop — APPROVED** [review]
LGTM!
