### PR TITLE
1. Standardise alias for lesson to be person + c  2. Edit msg in FindPersonCommand + AddPersonCommand + EditPersonCommand  3. Change regex check for handle and module code 4. Change regex check for remark 5. Fix cosmetic bug in result display

### LINKED ISSUE #161: [PE-D] Telegram handles should be capped at 30 characters
But it doesn't affect the inputting of valid telegram handles, so I guess it's fine.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jonas-chow/ped#2

### LINKED ISSUE #163: [PE-D] Cosmetic bug in Result Display
Step to reproduce:
1. `add n/Mary p/98765432 e/mary123@gmail.com m/CS2100 m/CS2030S T11 B09`

Result:
no space between CS2100 and CS2030S

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: nataniayp/ped#2

### LINKED ISSUE #166: [PE-D] Add student result output has missing space
For when adding multiple modules

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jonas-chow/ped#5

### LINKED ISSUE #167: [PE-D] Bug in Add Command (Module Code)
Step to reproduce:
1. `a n/Test2 e/test2@gmail.com m/CS2100XX`

Result:
- Contact is added nonetheless because add command allows for module code with more than one-letter suffix as stated below

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: nataniayp/ped#3

### LINKED ISSUE #169: [PE-D] Module codes are allowed to have arbitrarily long suffixes
The help messages also mention "optionally a one-letter suffix"

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jonas-chow/ped#6

### LINKED ISSUE #173: [PE-D] Find error message incorrect
Says 3 ways, but there are only 2

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jonas-chow/ped#8

### LINKED ISSUE #174: [PE-D] Wrong module code allowed
I edited m/CS1101SS and it was allowed to go through. In the user guide, it is said that only one letter is allowed.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: zhangchengchuan/ped#2

### LINKED ISSUE #177: [PE-D] Single-character remarks are not allowed
-------------
Labels: `severity.High` `type.FunctionalityBug`
original: jonas-chow/ped#10

### LINKED ISSUE #178: [PE-D] Any kind of module codes allowed
Same issue as before but this seems to be quite a big issue.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: zhangchengchuan/ped#3

### LINKED ISSUE #181: [PE-D] Inconsistency in command names
list classes should be lsc instead of lc.
All other commands follow the pattern of adding a c at the end of the existing command for contacts

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: jonas-chow/ped#12

### LINKED ISSUE #183: [PE-D] No new line before parameters for add command
-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jonas-chow/ped#13

### LINKED ISSUE #186: [PE-D] Inaccurate error message for invalid module input
Error message said only one-letter suffix is allowed but accept 2 letter suffix

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jeromewjj/ped#6

### LINKED ISSUE #189: [PE-D] Truncated remark field
Very long remark would result remark to be truncated. There is no way to view the entire remark. Possibly set a limit to the size of the remark?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jeromewjj/ped#7

### LINKED ISSUE #194: [PE-D] Example provided for edit is invalid
-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: NaokiShum/ped#5

### LINKED ISSUE #199: [PE-D] Accept invalid module code for addc command
addc command takes in module code cs2103ttttttt

input : addc m/CS2103TTTTTT T12 d/4 t/09:00 10:00 r/Online

expectation: error message for invalid module

actual: 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jeromewjj/ped#13

### PR DESCRIPTION
**Pull request by czhi-bin**
standardise alias
resolves #181 

change "three" to "two" for msg in find
resolves #173 

add new line and remove unwanted space in add
resolves #183 

add space between prefix
resolves #194 

change regex check for handle to set a max of 32 character
resolves #161 

change regex check for module code to check for the optional 1 character suffix
resolves #167 
resolves #169 
resolves #174 
resolves #178 
resolves #186 
resolves #199

change regex check for remark to limit to 52 characters long to prevent getting cut off in UI and to allow 1 character remark
resolves #177 
resolves #189

add space and comma between module codes 
resolves #163 
resolves #166

### CODE REVIEW

**Review by James-Kua — APPROVED** [review]
LGTM! Thanks for the fix!

File: src/main/java/seedu/address/model/person/Remark.java [hunk 1]
```diff
@@ -9,12 +9,14 @@
 public class Remark {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Remarks should only contain ASCII characters, and it should not be blank";
-    /*
+            "Remarks should only contain ASCII characters, and it should not be blank.\n"
+                    + "The limit for remark is 52 characters.";
```
Comment (tanruiquan) [inline src/main/java/seedu/address/model/person/Remark.java:13]:
```suggestion
            "Remarks should only contain ASCII characters and it should be at most 52 characters long.\n";
```

Comment (tanruiquan) [reply src/main/java/seedu/address/model/person/Remark.java:13]: I removed the `should not be blank` because remark can be blank - it is equivalent to not adding a remark

File: src/main/java/seedu/address/model/person/Person.java [hunk 2]
```diff
@@ -142,4 +142,15 @@ public String toString() {
...
+        StringBuilder sb = new StringBuilder();
+        ModuleCode[] array = moduleCodes.toArray(ModuleCode[]::new);
+        for (int i = 0; i < array.length; i++) {
+            sb.append(array[i]);
+            if (i != array.length - 1) {
+                sb.append(", ");
+            }
+        }
+        return sb.toString();
+    }
```
Comment (tanruiquan) [inline src/main/java/seedu/address/model/person/Person.java:155]: As opposed to doing this, would having this in the `ModuleCode` class be a better way of displaying?
```Java
@Override
    public String toString() {
        StringBuilder sb = new StringBuilder("[");
        sb.append(value);
        for (LessonCode lessonCode : lessonCodes) {
            sb.append(" ");
            sb.append(lessonCode);
        }
        sb.append("]");
        return sb.toString();
    }
```
It looks like this ⬇️ 
Screenshot 2021-11-01 at 8 11 30 PM

**Review by tanruiquan — APPROVED** [review]
Just a few comments, thanks for fixing the bugs 💯 LGTM!

File: src/main/java/seedu/address/model/person/Person.java (hunk 2 above)
Comment (James-Kua) [reply src/main/java/seedu/address/model/person/Person.java:155]: Do let me know if the display message for Add is changed, will need to update the screenshot accordingly in the UG.

File: src/main/java/seedu/address/model/person/Remark.java (hunk 1 above)
Comment (James-Kua) [reply src/main/java/seedu/address/model/person/Remark.java:13]: Then perhaps we should add a message indicating that `r/` followed by a whitespace, will remove the remark.

Comment (James-Kua) [reply src/main/java/seedu/address/model/person/Remark.java:13]: Remark should not be empty during Add, but can be empty during Edit, to remove the existing remark?

Comment (tanruiquan) [reply src/main/java/seedu/address/model/person/Remark.java:13]: If understand where you are coming from, but as it stands right now, the `isValidRemark()` would return `true` for an empty string. I am not sure if there is not a quick fix for that. I am afraid that this would be flag out as a `type.functionaliltyBug` because the behavior does not correspond to the description.

File: src/main/java/seedu/address/model/person/Person.java (hunk 2 above)
Comment (czhi-bin) [reply src/main/java/seedu/address/model/person/Person.java:155]: @James-Kua i gonna change

Comment (czhi-bin) [reply src/main/java/seedu/address/model/person/Person.java:155]: @tanruiquan i gonna use the [] but also separate the [] by comma or smth if not abit ugly 2 module code no separation

File: src/main/java/seedu/address/model/person/Remark.java (hunk 1 above)
Comment (czhi-bin) [reply src/main/java/seedu/address/model/person/Remark.java:13]: @tanruiquan but i feel that if u leave it as blank also got people can say featureflaw why can have blank remark

Comment (czhi-bin) [reply src/main/java/seedu/address/model/person/Remark.java:13]: @James-Kua @tanruiquan i think maybe just add in UG that the only time it can be blank is to remove existing remark using Edit?

File: src/main/java/seedu/address/model/person/Remark.java [hunk 3]
```diff
@@ -32,7 +33,7 @@ public Remark(String remark) {
      * Returns true if a given string is a valid remark.
      */
     public static boolean isValidRemark(String test) {
-        return test.equals("") || test.matches(VALIDATION_REGEX);
+        return test.equals("") || (test.matches(VALIDATION_REGEX) && test.length() <= 52 && !test.trim().isEmpty());
```
Comment (tanruiquan) [inline src/main/java/seedu/address/model/person/Remark.java:36]:
```suggestion
        return test.equals("") || (test.matches(VALIDATION_REGEX);
```

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 4]
```diff
@@ -87,6 +87,14 @@ public static Email parseEmail(String email) throws ParseException {
...
         requireNonNull(moduleCode);
         String trimmedModuleCode = moduleCode.trim();
+
+        if (trimmedModuleCode.contains("[")) {
+            trimmedModuleCode = trimmedModuleCode.substring(trimmedModuleCode.indexOf("[") + 1);
+        }
+        if (trimmedModuleCode.contains("]")) {
+            trimmedModuleCode = trimmedModuleCode.substring(0, trimmedModuleCode.indexOf("]"));
+        }
+
```
Comment (tanruiquan) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:97]: After adding this piece of code, the following input becomes valid:
`add n/name e/example@gmail.com m/[CS2100 T19]`

**Review by tanruiquan — COMMENTED** [review]
Sorry for the comments again but do you think there are better ways fix the tests case failing because the "quick fix" that you are using right now has some side effects

File: src/main/java/seedu/address/model/person/Person.java (hunk 2 above)
Comment (tanruiquan) [reply src/main/java/seedu/address/model/person/Person.java]: I have no objections here

File: src/main/java/seedu/address/model/person/Remark.java (hunk 3 above)
Comment (tanruiquan) [inline src/main/java/seedu/address/model/person/Remark.java:36]: This there a reason you left the `&& test.length() <= 52 && !test.trim().isEmpty()` there? The current regex check for both condition already.

File: src/main/java/seedu/address/model/person/Remark.java (hunk 1 above)
Comment (tanruiquan) [reply src/main/java/seedu/address/model/person/Remark.java]: @James-Kua @czhi-bin Even if we add in the UG, it does not stop users from inputting an empty remark `r/` when adding. Our current implementation would accept the input.

File: src/main/java/seedu/address/model/person/Remark.java (hunk 3 above)
Comment (czhi-bin) [reply src/main/java/seedu/address/model/person/Remark.java:36]: yes to pass test case of " "

Comment (tanruiquan) [reply src/main/java/seedu/address/model/person/Remark.java:36]: Ah thanks for pointing out, may i suggest using this `[\p{ASCII}&&[^ ]][\p{ASCII}]{1,51}` for the regex then

File: src/main/java/seedu/address/model/person/Remark.java [hunk 5]
```diff
@@ -9,12 +9,13 @@
...
-            "Remarks should only contain ASCII characters, and it should not be blank";
-    /*
+            "Remarks should only contain ASCII characters, and it should be at most 52 characters long.";
+
+    /**
      * The first character of the remark must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid remark.
      */
-    public static final String VALIDATION_REGEX = "[\\p{ASCII}]+[^\\s]";
+    public static final String VALIDATION_REGEX = "[\\p{ASCII}]{1,52}";
```
Comment (czhi-bin) [inline src/main/java/seedu/address/model/person/Remark.java:18]:
```suggestion
    public static final String VALIDATION_REGEX = "[\p{ASCII}&&[^ ]][\p{ASCII}]{0,51";
```

File: src/main/java/seedu/address/model/person/Remark.java [hunk 6]
```diff
@@ -9,12 +9,13 @@
...
-            "Remarks should only contain ASCII characters, and it should not be blank";
-    /*
+            "Remarks should only contain ASCII characters, and it should be at most 52 characters long.";
+
+    /**
      * The first character of the remark must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid remark.
      */
-    public static final String VALIDATION_REGEX = "[\\p{ASCII}]+[^\\s]";
+    public static final String VALIDATION_REGEX = "[\p{ASCII}&&[^ ]][\p{ASCII}]{0,51}";
```
Comment (czhi-bin) [inline src/main/java/seedu/address/model/person/Remark.java:18]:
```suggestion
    public static final String VALIDATION_REGEX = "[\\p{ASCII}&&[^ ]][\\p{ASCII}]{0,51}";
```

File: src/main/java/seedu/address/model/person/Remark.java (hunk 3 above)
Comment (czhi-bin) [reply src/main/java/seedu/address/model/person/Remark.java:36]: done
